// 77 Candidates Data - Generated 2026-02-01
const candidatesData = [
  {
    "name": "Sanjina Rao",
    "tier": "top",
    "score": 13,
    "phone": "1 808 269 7478",
    "experience": "Cashier/Cook",
    "education": "High school diploma or GED",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeSanjinaRao.pdf",
    "skills": ""
  },
  {
    "name": "Joshua Lee",
    "tier": "top",
    "score": 13,
    "phone": "1 808 464 2811",
    "experience": "Bartender",
    "education": "Upper secondary education - Arts",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJoshuaLee.pdf",
    "skills": ""
  },
  {
    "name": "Pieter  (Kobus) Breet",
    "tier": "top",
    "score": 12,
    "phone": "1 612 599 3136",
    "experience": "Shift Supervisor",
    "education": "",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumePieter(Kobus)Breet.pdf",
    "skills": ""
  },
  {
    "name": "Heather Fencl",
    "tier": "top",
    "score": 12,
    "phone": "1 808 226 0807",
    "experience": "Licensed Massage Therapist",
    "education": "",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHeatherFencl.pdf",
    "skills": ""
  },
  {
    "name": "Leilani Loveless",
    "tier": "top",
    "score": 11,
    "phone": "1 808 485 7865",
    "experience": "Cashier/Customer Service/Sales Associate/Stocker",
    "education": "",
    "date": "2026-02-09",
    "location": "Honolulu",
    "resume": true,
    "resumeFile": "ResumeLeilaniLoveless.pdf",
    "skills": ""
  },
  {
    "name": "Beyla Jones",
    "tier": "top",
    "score": 11,
    "phone": "1 970 497 6644",
    "experience": "Store Manager",
    "education": "",
    "date": "2026-02-08",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeBeylaJones.pdf",
    "skills": ""
  },
  {
    "name": "Catherine Piano",
    "tier": "top",
    "score": 11,
    "phone": "385 95 815 4518",
    "experience": "SENIOR WAITRESS",
    "education": "",
    "date": "2026-02-08",
    "location": "10000",
    "resume": true,
    "resumeFile": "ResumeCatherinePiano.pdf",
    "skills": ""
  },
  {
    "name": "Emily Newell",
    "tier": "top",
    "score": 11,
    "phone": "1 408 876 0313",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-08",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeEmilyNewell.pdf",
    "skills": ""
  },
  {
    "name": "Hallie Dugan",
    "tier": "top",
    "score": 11,
    "phone": "1 816 585 4140",
    "experience": "Game Guide",
    "education": "High school diploma or GED",
    "date": "2026-02-08",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHallieDugan.pdf",
    "skills": ""
  },
  {
    "name": "Camilo Haro",
    "tier": "top",
    "score": 11,
    "phone": "1 808 437 9982",
    "experience": "Cashier",
    "education": "",
    "date": "2026-02-08",
    "location": "Honolulu",
    "resume": true,
    "resumeFile": "ResumeCamiloHaro.pdf",
    "skills": ""
  },
  {
    "name": "Carla Silva",
    "tier": "top",
    "score": 11,
    "phone": "1 808 501 8640",
    "experience": "Server",
    "education": "College - Hotel and restaurant administration",
    "date": "2026-02-07",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeCarlaSilva.pdf",
    "skills": ""
  },
  {
    "name": "Donna Sowell",
    "tier": "top",
    "score": 11,
    "phone": "1 808 562 6861",
    "experience": "McDonalds Crew Member",
    "education": "Graduate - Reatil",
    "date": "2026-02-07",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeDonnaSowell.pdf",
    "skills": ""
  },
  {
    "name": "Nevaeh Berman",
    "tier": "top",
    "score": 11,
    "phone": "1 541 880 8743",
    "experience": "",
    "education": "",
    "date": "2026-02-06",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeNevaehBerman.pdf",
    "skills": ""
  },
  {
    "name": "An Li Allison",
    "tier": "top",
    "score": 11,
    "phone": "1 651 399 9193",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-06",
    "location": "Honolulu, Hawaii",
    "resume": true,
    "resumeFile": "ResumeAnLiAllison.pdf",
    "skills": ""
  },
  {
    "name": "Alexandra Xua",
    "tier": "top",
    "score": 11,
    "phone": "1 808 445 3589",
    "experience": "Barista",
    "education": "Whatcom community College - A.A.S.",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeAlexandraXua.pdf",
    "skills": ""
  },
  {
    "name": "Ava Fairbrother",
    "tier": "top",
    "score": 11,
    "phone": "1 607 426 1260",
    "experience": "Cashier",
    "education": "College - Criminal Justice",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeAvaFairbrother.pdf",
    "skills": ""
  },
  {
    "name": "LUCY POOL",
    "tier": "top",
    "score": 11,
    "phone": "1 818 621 5407",
    "experience": "Morning brew- barista",
    "education": "",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeLUCYPOOL.pdf",
    "skills": ""
  },
  {
    "name": "Haruna Emmer",
    "tier": "top",
    "score": 11,
    "phone": "1 808 721 0938",
    "experience": "Barista",
    "education": "",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHarunaEmmer.pdf",
    "skills": ""
  },
  {
    "name": "Kiley Butkus",
    "tier": "top",
    "score": 11,
    "phone": "1 949 212 4425",
    "experience": "Food Runner/Server",
    "education": "High school diploma",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeKileyButkus.pdf",
    "skills": ""
  },
  {
    "name": "Madison Pasaoa",
    "tier": "top",
    "score": 11,
    "phone": "1 808 348 4078",
    "experience": "Gelato Server",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, Hi",
    "resume": false,
    "resumeFile": null,
    "skills": ""
  },
  {
    "name": "Sayaka Gaspard",
    "tier": "top",
    "score": 11,
    "phone": "1 702 591 2265",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-04",
    "location": "'Ewa Beach, HI",
    "resume": true,
    "resumeFile": "ResumeSayakaGaspard.pdf",
    "skills": ""
  },
  {
    "name": "Honesty-Marie Riley",
    "tier": "top",
    "score": 11,
    "phone": "1 808 583 4590",
    "experience": "Sales Associate",
    "education": "GED",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHonesty-MarieRiley.pdf",
    "skills": ""
  },
  {
    "name": "Hannah Quick",
    "tier": "top",
    "score": 11,
    "phone": "1 703 675 9743",
    "experience": "Hostess/Server",
    "education": "High school diploma or GED",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHannahQuick.pdf",
    "skills": ""
  },
  {
    "name": "MARIANA FIGUEROA",
    "tier": "top",
    "score": 11,
    "phone": "1 334 400 9616",
    "experience": "barista",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, HI, 96822, US",
    "resume": true,
    "resumeFile": "ResumeMARIANAFIGUEROA.pdf",
    "skills": ""
  },
  {
    "name": "kay ornatowski",
    "tier": "top",
    "score": 11,
    "phone": "1 574 374 8909",
    "experience": "Sales Associate",
    "education": "High school diploma",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "Resumekayornatowski.pdf",
    "skills": ""
  },
  {
    "name": "Alexis Shulga",
    "tier": "top",
    "score": 11,
    "phone": "1 808 304 3743",
    "experience": "Barista",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, Hawaii, US",
    "resume": true,
    "resumeFile": "ResumeAlexisShulga.pdf",
    "skills": ""
  },
  {
    "name": "Kim Le",
    "tier": "top",
    "score": 11,
    "phone": "1 808 866 6078",
    "experience": "Cashier",
    "education": "Upper secondary education",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeKimLe.pdf",
    "skills": ""
  },
  {
    "name": "Dorian Covahey",
    "tier": "top",
    "score": 11,
    "phone": "1 808 206 0972",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeDorianCovahey.pdf",
    "skills": ""
  },
  {
    "name": "Parrish Viator",
    "tier": "top",
    "score": 11,
    "phone": "1 360 390 1257",
    "experience": "Barista",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI, US",
    "resume": true,
    "resumeFile": "ResumeParrishViator.pdf",
    "skills": ""
  },
  {
    "name": "Dwayne Kahoonei",
    "tier": "top",
    "score": 11,
    "phone": "1 808 699 4319",
    "experience": "Cashier",
    "education": "High school diploma",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeDwayneKahoonei.pdf",
    "skills": ""
  },
  {
    "name": "Huyen - Tran Ha Dang",
    "tier": "top",
    "score": 11,
    "phone": "1 808 763 1183",
    "experience": "Retail Sales Associate/Cashier",
    "education": "High school diploma",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHuyen-TranHaDang.pdf",
    "skills": ""
  },
  {
    "name": "Aurora Marcy",
    "tier": "top",
    "score": 11,
    "phone": "1 360 229 3800",
    "experience": "Photographer",
    "education": "High school diploma",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeAuroraMarcy.pdf",
    "skills": ""
  },
  {
    "name": "Leah Kliem",
    "tier": "top",
    "score": 11,
    "phone": "1 619 607 8689",
    "experience": "After School Program Manager",
    "education": "Bachelor of Arts - Clinical Psychology",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeLeahKliem.pdf",
    "skills": ""
  },
  {
    "name": "EDMELYN HAZLEWOOD",
    "tier": "top",
    "score": 11,
    "phone": "1 808 485 9914",
    "experience": "Customer Service Reservation Agent",
    "education": "Bachelor of Science - Information Technology",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeEDMELYNHAZLEWOOD.pdf",
    "skills": ""
  },
  {
    "name": "Ira Rose",
    "tier": "top",
    "score": 11,
    "phone": "1 808 321 2184",
    "experience": "Assistant Barista",
    "education": "Greenbrier high school graduate",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeIraRose.pdf",
    "skills": ""
  },
  {
    "name": "Lawson McNeely",
    "tier": "top",
    "score": 11,
    "phone": "1 321 506 4212",
    "experience": "Barista",
    "education": "Bachelors - Psychology",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeLawsonMcNeely.pdf",
    "skills": ""
  },
  {
    "name": "Jason Riddle",
    "tier": "top",
    "score": 11,
    "phone": "1 203 464 3984",
    "experience": "Server",
    "education": "",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJasonRiddle.pdf",
    "skills": ""
  },
  {
    "name": "Jaelah Muñoz",
    "tier": "top",
    "score": 11,
    "phone": "1 916 479 0569",
    "experience": "",
    "education": "",
    "date": "2026-02-02",
    "location": "Honolulu, HI, US",
    "resume": true,
    "resumeFile": "ResumeJaelahMuñoz.pdf",
    "skills": ""
  },
  {
    "name": "Marcela Naomi Huaccho Choque",
    "tier": "top",
    "score": 11,
    "phone": "1 808 206 1609",
    "experience": "",
    "education": "",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeMarcelaNaomiHuacchoChoque.pdf",
    "skills": ""
  },
  {
    "name": "Gary Basuil",
    "tier": "strong",
    "score": 10,
    "phone": "1 808 779 3552",
    "experience": "Host",
    "education": "High school diploma",
    "date": "2026-02-08",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeGaryBasuil.pdf",
    "skills": ""
  },
  {
    "name": "Jaylyn Wharton",
    "tier": "strong",
    "score": 10,
    "phone": "1 808 452 3031",
    "experience": "Barista",
    "education": "",
    "date": "2026-02-07",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJaylynWharton.pdf",
    "skills": ""
  },
  {
    "name": "BENJAMIN AQUINO",
    "tier": "strong",
    "score": 10,
    "phone": "1 808 205 8546",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI 96822",
    "resume": true,
    "resumeFile": "ResumeBENJAMINAQUINO.pdf",
    "skills": ""
  },
  {
    "name": "Isabella Mendoza",
    "tier": "strong",
    "score": 9,
    "phone": "1 760 271 7936",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-06",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeIsabellaMendoza.pdf",
    "skills": ""
  },
  {
    "name": "Christian Melegrito",
    "tier": "strong",
    "score": 9,
    "phone": "1 808 673 0306",
    "experience": "Sales Associate",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeChristianMelegrito.pdf",
    "skills": ""
  },
  {
    "name": "Tdlyn Frank",
    "tier": "strong",
    "score": 9,
    "phone": "1 808 970 8165",
    "experience": "Cashier",
    "education": "High school",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeTdlynFrank.pdf",
    "skills": ""
  },
  {
    "name": "Naomi Hosford",
    "tier": "strong",
    "score": 9,
    "phone": "1 818 429 5146",
    "experience": "",
    "education": "",
    "date": "2026-02-01",
    "location": "La Cañada Flintridge, CA",
    "resume": true,
    "resumeFile": "ResumeNaomiHosford.pdf",
    "skills": ""
  },
  {
    "name": "Giang Tran",
    "tier": "good",
    "score": 8,
    "phone": "1 808 991 5208",
    "experience": "Crew Member",
    "education": "High school",
    "date": "2026-02-08",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeGiangTran.pdf",
    "skills": ""
  },
  {
    "name": "Alana Image",
    "tier": "good",
    "score": 8,
    "phone": "1 415 954 2067",
    "experience": "Retail Sales Associate",
    "education": "Undergraduate - Psychology, Art",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeAlanaImage.pdf",
    "skills": ""
  },
  {
    "name": "Madison Beardsley",
    "tier": "good",
    "score": 8,
    "phone": "1 808 773 6392",
    "experience": "Waitress/Cashier",
    "education": "",
    "date": "2026-02-02",
    "location": "Pearl City, HI",
    "resume": true,
    "resumeFile": "ResumeMadisonBeardsley.pdf",
    "skills": ""
  },
  {
    "name": "Emma Gretsch",
    "tier": "good",
    "score": 8,
    "phone": "1 760 840 0098",
    "experience": "Food Runner",
    "education": "",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeEmmaGretsch.pdf",
    "skills": ""
  },
  {
    "name": "Rina Robert",
    "tier": "good",
    "score": 8,
    "phone": "1 808 393 1562",
    "experience": "Sales Associate/Cashier",
    "education": "",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeRinaRobert.pdf",
    "skills": ""
  },
  {
    "name": "Janelle Cabanit",
    "tier": "good",
    "score": 7,
    "phone": "1 808 670 9544",
    "experience": "Barista/Cashier",
    "education": "",
    "date": "2026-02-09",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJanelleCabanit.pdf",
    "skills": ""
  },
  {
    "name": "Sky Brown",
    "tier": "good",
    "score": 7,
    "phone": "1 808 743 1407",
    "experience": "",
    "education": "",
    "date": "2026-02-06",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeSkyBrown.pdf",
    "skills": ""
  },
  {
    "name": "Eliana Carnes",
    "tier": "good",
    "score": 7,
    "phone": "1 562 286 4506",
    "experience": "Barista",
    "education": "",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeElianaCarnes.pdf",
    "skills": ""
  },
  {
    "name": "Austin M",
    "tier": "good",
    "score": 7,
    "phone": "1 808 379 8660",
    "experience": "",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeAustinM.pdf",
    "skills": ""
  },
  {
    "name": "Emmanuel Ridgley",
    "tier": "good",
    "score": 7,
    "phone": "1 702 788 8397",
    "experience": "Sales Associate",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeEmmanuelRidgley.pdf",
    "skills": ""
  },
  {
    "name": "cheyenne Bailey",
    "tier": "good",
    "score": 7,
    "phone": "1 808 282 6775",
    "experience": "Cashier/Customer Service",
    "education": "Upper secondary education",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumecheyenneBailey.pdf",
    "skills": ""
  },
  {
    "name": "Mia Arreza",
    "tier": "good",
    "score": 7,
    "phone": "1 808 772 0356",
    "experience": "Bird Specialist",
    "education": "",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeMiaArreza.pdf",
    "skills": ""
  },
  {
    "name": "Chantal Marie Cacpal",
    "tier": "fair",
    "score": 6,
    "phone": "1 808 542 7453",
    "experience": "",
    "education": "",
    "date": "2026-02-08",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeChantalMarieCacpal.pdf",
    "skills": ""
  },
  {
    "name": "Jasmine Boyd",
    "tier": "fair",
    "score": 6,
    "phone": "1 980 358 9475",
    "experience": "Guest Services Representative",
    "education": "University - Marine Biology",
    "date": "2026-02-07",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJasmineBoyd.pdf",
    "skills": ""
  },
  {
    "name": "Trucy Thomas",
    "tier": "fair",
    "score": 6,
    "phone": "1 808 478 0683",
    "experience": "Forklift Operator",
    "education": "Hawaii National Guard - HISET",
    "date": "2026-02-06",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeTrucyThomas.pdf",
    "skills": ""
  },
  {
    "name": "Hayden Bode",
    "tier": "fair",
    "score": 6,
    "phone": "1 859 653 6910",
    "experience": "Tour Guide",
    "education": "",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHaydenBode.pdf",
    "skills": ""
  },
  {
    "name": "Rachanne Miquel",
    "tier": "fair",
    "score": 6,
    "phone": "1 808 391 3222",
    "experience": "Popeyes crew member",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeRachanneMiquel.pdf",
    "skills": ""
  },
  {
    "name": "Jmark Rivera",
    "tier": "fair",
    "score": 6,
    "phone": "1 254 290 4177",
    "experience": "",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJmarkRivera.pdf",
    "skills": ""
  },
  {
    "name": "Brooke Violette",
    "tier": "fair",
    "score": 6,
    "phone": "1 541 852 1615",
    "experience": "Deli Attendant",
    "education": "",
    "date": "2026-02-03",
    "location": "2579 Dole Street Rm 452, Honolulu, HI 96822",
    "resume": true,
    "resumeFile": "ResumeBrookeViolette.pdf",
    "skills": ""
  },
  {
    "name": "Tyler Crawford",
    "tier": "fair",
    "score": 5,
    "phone": "1 858 605 8395",
    "experience": "Server Assistant",
    "education": "In college - Business",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeTylerCrawford.pdf",
    "skills": ""
  },
  {
    "name": "Jameson O'Connell",
    "tier": "fair",
    "score": 5,
    "phone": "1 262 808 7822",
    "experience": "Cashier",
    "education": "",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJamesonO'Connell.pdf",
    "skills": ""
  },
  {
    "name": "AUBREY GRIMES",
    "tier": "fair",
    "score": 5,
    "phone": "1 512 638 5014",
    "experience": "Spa Attendant",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI, 96822, US",
    "resume": true,
    "resumeFile": "ResumeAUBREYGRIMES.pdf",
    "skills": ""
  },
  {
    "name": "Hirut Denver",
    "tier": "fair",
    "score": 5,
    "phone": "1 541 908 7194",
    "experience": "Drink Maker/Cashier",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeHirutDenver.pdf",
    "skills": ""
  },
  {
    "name": "Kenneth Liu",
    "tier": "weak",
    "score": 4,
    "phone": "1 808 429 1346",
    "experience": "",
    "education": "",
    "date": "2026-02-05",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeKennethLiu.pdf",
    "skills": ""
  },
  {
    "name": "Leila Zaragoza",
    "tier": "weak",
    "score": 4,
    "phone": "1 805 514 4116",
    "experience": "Sales Associate",
    "education": "Bachelor's degree - Mechanical Engineering",
    "date": "2026-02-01",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeLeilaZaragoza.pdf",
    "skills": ""
  },
  {
    "name": "CAROLINE COOK",
    "tier": "weak",
    "score": 3,
    "phone": "1 865 454 7323",
    "experience": "Sales Associate",
    "education": "Certificate - Phlebotomy",
    "date": "2026-02-06",
    "location": "Fort Shafter, HI",
    "resume": true,
    "resumeFile": "ResumeCAROLINECOOK.pdf",
    "skills": ""
  },
  {
    "name": "Mayforeen Albert",
    "tier": "weak",
    "score": 3,
    "phone": "1 808 520 6899",
    "experience": "",
    "education": "High School Education",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeMayforeenAlbert.pdf",
    "skills": ""
  },
  {
    "name": "Ashley Miyata",
    "tier": "weak",
    "score": 3,
    "phone": "1 808 286 3088",
    "experience": "",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeAshleyMiyata.pdf",
    "skills": ""
  },
  {
    "name": "James Reyes",
    "tier": "weak",
    "score": 2,
    "phone": "1 808 849 3687",
    "experience": "",
    "education": "",
    "date": "2026-02-04",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJamesReyes.pdf",
    "skills": ""
  },
  {
    "name": "Jendelyn Duhaylongsod",
    "tier": "weak",
    "score": 2,
    "phone": "1 808 425 1465",
    "experience": "None",
    "education": "",
    "date": "2026-02-02",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeJendelynDuhaylongsod.pdf",
    "skills": ""
  },
  {
    "name": "Kainoa Valdez",
    "tier": "weak",
    "score": 1,
    "phone": "1 808 724 2683",
    "experience": "",
    "education": "",
    "date": "2026-02-03",
    "location": "Honolulu, HI",
    "resume": true,
    "resumeFile": "ResumeKainoaValdez.pdf",
    "skills": ""
  }
];
